dependencies:
- python=3.11.4
- pip=23.2.1
- pip:
  - black==22.10.0
  - jupyter==1.0.0
  - jupyter_contrib_nbextensions==0.7.0
  - jupytext==1.14.1
  - matplotlib==3.6.2
  - nb_black==1.0.7
  - numpy==1.23.5
  - pandas==1.5.2
  - papermill==2.4.0
  - scikit-learn==1.1.3
  - seaborn==0.12.1
